/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.8 2004/01/06 19:03:44 nectar Exp $
 */

#if defined(__FreeBSD__)
#include <sys/cdefs.h>
#else
#define __unused
#endif

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) __unused;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
static yyconst short int yy_accept[301] =
    {   0,
       69,   69,   15,   15,   73,   72,   70,   71,   72,    2,
        5,   14,   11,   13,   72,   67,   67,    4,   12,    6,
       66,   66,   66,   66,   66,   66,   66,   66,    7,    8,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,    9,   10,   15,   72,    0,    3,    0,
       67,   69,   69,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   15,    0,    0,
       17,    0,    1,   67,   68,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   38,   66,   66,   66,   23,   66,   66,   19,
       66,   66,   25,   62,   66,   31,   66,   66,   66,   66,
       20,   66,   66,    0,   16,   67,   68,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   51,   66,
       66,   66,   66,   66,   66,   66,   63,   66,   66,   66,
       66,   66,    0,   30,   66,    0,   66,   53,   56,   28,
       66,   66,   66,   32,   67,   68,   64,   66,   66,   66,
       66,   66,   66,   52,   66,   48,   66,   66,   66,   66,
       66,   66,   66,   66,   54,   21,   66,   66,   58,    0,

        0,   66,    0,   66,   66,   33,   66,   67,   68,   66,
       66,   22,   43,   66,   66,   49,   46,   66,   66,   66,
       66,   66,   36,   66,   66,   57,   66,   18,    0,   66,
       24,   61,   66,   66,   67,   68,   66,   34,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   55,   65,   29,
       27,   60,   59,   67,   68,   66,   66,   66,   66,   66,
       66,   44,   66,   66,   66,    0,   67,   68,   66,   66,
       66,   66,   66,   45,   47,   66,   66,    0,   67,   68,
       66,   66,   40,   66,   50,   66,   66,   26,   69,   66,
       41,   66,   66,   66,   42,   39,   66,   37,   35,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    1,    1,
        1,    8,    9,   10,   11,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,    1,
       16,    1,    1,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   24,   24,   27,   28,   29,   30,   31,
       24,   32,   33,   34,   35,   36,   37,   24,   38,   24,
       39,    1,   40,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   24,   24,   51,   52,   53,
       54,   55,   24,   56,   57,   58,   59,   60,   61,   62,
       63,   24,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        3,    1,    4,    4,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[310] =
    {   0,
        0,    0,   64,   68,  696,  697,  697,  697,    0,  697,
      697,  697,  697,  697,   59,   61,   63,  697,  697,  697,
      684,   67,   68,   69,   70,   71,   72,   73,  697,  697,
       74,   75,   76,   77,   79,   80,   78,   82,   83,   85,
       88,   91,   89,  697,  697,   93,    0,  689,  697,  690,
       90,    0,  133,    0,  681,   97,   99,  117,  138,   87,
       96,  139,  163,  100,  129,  148,  147,  150,  154,  151,
      152,  155,  156,  157,  158,  159,  161,  162,  171,  172,
      177,  174,  180,  184,  187,  188,  191,  208,  686,  685,
      697,  686,  697,   92,  237,  196,  192,  210,  204,  206,

      207,  213,  211,  216,  209,  215,  265,  220,  225,  219,
      228,  226,  677,  230,  236,  251,  676,  253,  231,  262,
      256,  235,  286,  257,  259,  675,  258,  263,  267,  280,
      674,  282,  285,  679,  697,  285,  327,  284,  295,  292,
      299,  300,  298,  297,  305,  301,  302,  304,  672,  306,
      309,  310,  303,  316,  311,  317,  671,  325,  327,  333,
      345,  346,  623,  354,  348,  622,  349,  668,  667,  666,
      350,  351,  352,  665,  353,  401,  664,  353,  357,  366,
      368,  364,  367,  663,  369,  662,  372,  376,  382,  370,
      381,  387,  377,  375,  389,  661,  378,  383,  660,  616,

      611,  390,  614,  380,  407,  640,  416,  417,  458,  392,
      422,  634,  626,  428,  426,  624,  623,  429,  431,  438,
      440,  439,  621,  441,  442,  619,  443,  697,  575,  444,
      697,  617,  445,  453,  452,  494,  458,  614,  462,  452,
      477,  472,  481,  473,  500,  474,  448,  612,  611,  697,
      482,  610,  609,  508,  529,  512,  476,  514,  519,  522,
      523,  608,  516,  515,  518,  560,  542,  565,  517,  535,
      546,  520,  547,  606,  605,  554,  550,  561,  553,    0,
      558,  570,  602,  551,  595,  571,  579,  697,  578,  582,
      593,  583,  584,  587,  591,  590,  585,  589,  588,  697,

      639,  643,  531,  645,  649,  653,  657,  659,  663
    } ;

static yyconst short int yy_def[310] =
    {   0,
      300,    1,  301,  301,  300,  300,  300,  300,  302,  300,
      300,  300,  300,  300,  300,  303,  303,  300,  300,  300,
      304,  304,  304,  304,  304,  304,  304,  304,  300,  300,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  300,  300,  300,  305,  306,  300,  307,
      303,  303,  303,  308,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  300,  309,  306,
      300,  307,  300,  303,  303,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  309,  300,  303,  303,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  300,  304,  304,  300,  304,  304,  304,  304,
      304,  304,  304,  304,  303,  303,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  300,

      300,  304,  300,  304,  304,  304,  304,  303,  303,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  300,  300,  304,
      300,  304,  304,  304,  303,  303,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  300,
      304,  304,  304,  303,  303,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  300,  303,  303,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  300,  303,  303,
      304,  304,  304,  304,  304,  304,  304,  300,  303,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,    0,

      300,  300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst short int yy_nxt[763] =
    {   0,
        6,    6,    7,    8,    9,   10,   11,    6,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   22,   21,   21,   23,   21,   21,   21,   24,
       25,   26,   27,   28,   21,   21,   21,   21,   29,   30,
       21,   31,   21,   32,   21,   33,   34,   21,   21,   35,
       36,   37,   38,   21,   21,   39,   40,   21,   41,   42,
       43,   21,   21,   44,   45,   46,   49,   46,   47,   46,
       50,   46,   47,   51,   51,   51,   51,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   61,   54,   54,   88,   54,   88,   54,   54,   54,

       60,   54,   94,   94,  136,  136,   54,   54,   56,   54,
       54,  100,   63,   64,  101,   58,   62,   65,   71,   75,
       57,   59,   53,   76,   79,   69,   68,   54,   67,   66,
       72,   73,   85,   74,   77,   70,   86,   81,   87,   54,
       78,   80,   82,   83,   84,   95,   95,   96,   54,   54,
       95,   95,   95,   95,   95,   95,   97,   54,   54,  109,
       54,   54,   54,   98,   54,   54,   54,   54,   54,   54,
      110,   54,   54,   54,   95,   95,   95,   95,   95,   95,
      103,   54,   54,  104,   54,  105,  102,   54,   99,  111,
       54,  106,  107,  108,   54,  114,  115,   54,   54,  118,

      119,   54,   54,  116,  120,  112,   54,  121,  123,   88,
      117,   88,  113,  124,   54,  122,   54,   54,  127,   54,
       54,   54,  129,   54,  126,   54,   54,  128,  125,   54,
       54,  148,  149,  130,  143,   54,   54,  139,   54,  145,
       54,   54,  131,  132,  147,   54,   54,  146,  133,  137,
      137,  153,  138,  141,  137,  137,  137,  137,  137,  137,
      140,   54,  144,   54,  142,  163,   54,   54,   54,   54,
      154,  157,   54,   54,  155,   54,  162,   54,  137,  137,
      137,  137,  137,  137,  150,  156,  158,  151,  159,  166,
       54,  165,   54,  152,   54,   54,   54,  175,  175,  167,

      160,  169,   54,  161,  168,   54,  164,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,  170,  185,   54,
       54,   54,  186,  187,  171,  188,   54,   54,  191,  177,
      182,  189,  172,  174,  192,   54,  190,   54,  173,  176,
      176,  179,  184,   54,  176,  176,  176,  176,  176,  176,
      178,  180,  181,  183,  193,   54,   54,  201,   54,   54,
       54,   54,   54,   54,   54,  208,  208,   54,  176,  176,
      176,  176,  176,  176,   54,  194,   54,   54,   54,   54,
       54,  195,   54,  197,  196,   54,   54,   54,   54,  202,
       54,   54,   54,   54,  204,  220,  217,   54,  206,   54,

       54,  207,   54,  198,  214,  210,  216,  199,  219,  211,
      218,  212,  205,  209,  209,  213,  221,   54,  209,  209,
      209,  209,  209,  209,  215,  223,   54,  227,  222,  235,
      235,  224,   54,  237,  225,  232,   54,  230,   54,   54,
      226,   54,  209,  209,  209,  209,  209,  209,   54,   54,
       54,   54,   54,   54,   54,   54,  243,  245,   54,  242,
      247,  233,   54,   54,  254,  254,  244,  238,   54,  234,
      236,  236,   54,  239,  240,  236,  236,  236,  236,  236,
      236,  241,   54,   54,   54,  266,   54,   54,  249,  251,
      252,   54,   54,  258,  262,  246,  265,  260,  248,  236,

      236,  236,  236,  236,  236,  253,  255,  255,  256,  261,
       54,  255,  255,  255,  255,  255,  255,  257,  259,  263,
      267,  267,   54,  264,   54,   54,   54,   54,   54,   54,
       54,  270,   54,   54,   52,  255,  255,  255,  255,  255,
      255,  268,  268,  273,  274,   54,  268,  268,  268,  268,
      268,  268,  269,  275,  279,  279,   54,   54,  276,  277,
       54,   54,  281,  271,   54,  289,  289,  285,   54,  284,
      268,  268,  268,  268,  268,  268,  272,  280,  280,  286,
       54,   54,  280,  280,  280,  280,  280,  280,  282,   54,
      289,  289,   54,   54,   54,   54,  283,   54,   54,   54,

       54,   54,  287,   54,  292,   54,  280,  280,  280,  280,
      280,  280,   54,  290,  288,   54,   54,  278,   54,   54,
       54,   54,   54,  293,   54,  291,  294,   54,  250,   54,
      297,   54,  298,   54,   54,  296,   54,  295,  299,    6,
        6,    6,    6,   48,   54,   48,   48,   55,   55,   89,
       54,   89,   89,   90,   90,   90,   90,   92,   92,   92,
       92,   54,   54,  134,  134,  134,  134,  231,  229,  228,
       54,   54,   54,   54,   54,   54,   54,   54,   54,  203,
      200,   54,   54,  135,   54,   54,   54,   54,   93,   91,
      135,   54,   93,   91,   54,  300,    5,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300
    } ;

static yyconst short int yy_chk[763] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,   15,    3,    3,    4,
       15,    4,    4,   16,   16,   17,   17,   22,   23,   24,
       25,   26,   27,   28,   31,   32,   33,   34,   37,   35,
       36,   26,   38,   39,   46,   40,   46,   60,   41,   43,

       25,   42,   51,   51,   94,   94,   61,   56,   22,   57,
       64,   60,   27,   27,   61,   24,   26,   27,   34,   37,
       23,   24,   16,   37,   39,   32,   31,   58,   28,   27,
       34,   35,   42,   36,   37,   33,   42,   40,   43,   65,
       38,   39,   40,   40,   41,   53,   53,   56,   59,   62,
       53,   53,   53,   53,   53,   53,   57,   67,   66,   64,
       68,   70,   71,   58,   69,   72,   73,   74,   75,   76,
       65,   77,   78,   63,   53,   53,   53,   53,   53,   53,
       63,   79,   80,   63,   82,   63,   62,   81,   59,   66,
       83,   63,   63,   63,   84,   69,   70,   85,   86,   73,

       73,   87,   97,   71,   74,   67,   96,   75,   77,   88,
       72,   88,   68,   78,   99,   76,  100,  101,   81,  105,
       98,  103,   83,  102,   80,  106,  104,   82,   79,  110,
      108,  105,  106,   84,  101,  109,  112,   97,  111,  103,
      114,  119,   85,   86,  104,  122,  115,  103,   87,   95,
       95,  108,   96,   99,   95,   95,   95,   95,   95,   95,
       98,  116,  102,  118,  100,  120,  121,  124,  127,  125,
      109,  112,  120,  128,  110,  107,  119,  129,   95,   95,
       95,   95,   95,   95,  107,  111,  114,  107,  115,  123,
      130,  122,  132,  107,  138,  133,  123,  136,  136,  124,

      116,  127,  140,  118,  125,  139,  121,  144,  143,  141,
      142,  146,  147,  153,  148,  145,  150,  128,  146,  151,
      152,  155,  147,  148,  129,  150,  154,  156,  153,  138,
      143,  151,  130,  133,  154,  158,  152,  159,  132,  137,
      137,  140,  145,  160,  137,  137,  137,  137,  137,  137,
      139,  141,  142,  144,  155,  161,  162,  164,  165,  167,
      171,  172,  173,  178,  164,  175,  175,  179,  137,  137,
      137,  137,  137,  137,  182,  156,  180,  183,  181,  185,
      190,  158,  187,  160,  159,  194,  188,  193,  197,  165,
      204,  191,  189,  198,  167,  190,  187,  192,  172,  195,

      202,  173,  210,  161,  182,  178,  185,  162,  189,  179,
      188,  180,  171,  176,  176,  181,  191,  205,  176,  176,
      176,  176,  176,  176,  183,  193,  207,  198,  192,  208,
      208,  194,  211,  210,  195,  204,  215,  202,  214,  218,
      197,  219,  176,  176,  176,  176,  176,  176,  220,  222,
      221,  224,  225,  227,  230,  233,  219,  221,  247,  218,
      224,  205,  240,  234,  235,  235,  220,  211,  237,  207,
      209,  209,  239,  214,  214,  209,  209,  209,  209,  209,
      209,  215,  242,  244,  246,  251,  257,  241,  227,  230,
      233,  243,  251,  240,  244,  222,  247,  242,  225,  209,

      209,  209,  209,  209,  209,  234,  236,  236,  237,  243,
      245,  236,  236,  236,  236,  236,  236,  239,  241,  245,
      254,  254,  256,  246,  258,  264,  263,  269,  265,  259,
      272,  257,  260,  261,  303,  236,  236,  236,  236,  236,
      236,  255,  255,  260,  261,  270,  255,  255,  255,  255,
      255,  255,  256,  263,  267,  267,  271,  273,  264,  265,
      277,  284,  269,  258,  276,  279,  279,  273,  281,  272,
      255,  255,  255,  255,  255,  255,  259,  268,  268,  276,
      282,  286,  268,  268,  268,  268,  268,  268,  270,  287,
      289,  289,  290,  292,  293,  297,  271,  294,  299,  298,

      296,  295,  277,  291,  284,  285,  268,  268,  268,  268,
      268,  268,  283,  281,  278,  275,  274,  266,  262,  253,
      252,  249,  248,  286,  238,  282,  287,  232,  229,  226,
      293,  223,  294,  217,  216,  292,  213,  290,  297,  301,
      301,  301,  301,  302,  212,  302,  302,  304,  304,  305,
      206,  305,  305,  306,  306,  306,  306,  307,  307,  307,
      307,  308,  308,  309,  309,  309,  309,  203,  201,  200,
      199,  196,  186,  184,  177,  174,  170,  169,  168,  166,
      163,  157,  149,  134,  131,  126,  117,  113,   92,   90,
       89,   55,   50,   48,   21,    5,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config/actions/actions.l"
#define INITIAL 0
#line 2 "config/actions/actions.l"

#include "includes.h"

void skipcmnts ();
void skipcmnts2 ();

typedef struct include_struct
{
   YY_BUFFER_STATE buffer;
   char filename[255];
   int line_number;
   
} include_struct;


include_struct include_stack[MAX_INCLUDE_DEPTH];

#define incl 1

#line 663 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 35 "config/actions/actions.l"


#line 817 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 697 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "config/actions/actions.l"
{   /* COMMENT */; line_number++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "config/actions/actions.l"
{   skipcmnts2(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "config/actions/actions.l"
{   skipcmnts (); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) 
                    {
		       return(T_END_RULE);
		    }
		    else
		    {
		       return(T_END_RULE1);
		    }
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "config/actions/actions.l"
{   return('$'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "config/actions/actions.l"
{   return('@'); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "config/actions/actions.l"
{   return('['); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "config/actions/actions.l"
{   return(']'); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "config/actions/actions.l"
{   return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "config/actions/actions.l"
{   return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "config/actions/actions.l"
{   return(','); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "config/actions/actions.l"
{   return('='); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "config/actions/actions.l"
{   return(T_MIN_OP); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "config/actions/actions.l"
{   return(T_PLS_OP); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "config/actions/actions.l"
{/* eat the whitespace */}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "config/actions/actions.l"
{ 

   /* got the include file name */
   if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
   {
      yyerror("Includes nested too deeply. Operator skiped.");
      BEGIN(INITIAL);
   }
   else
   {
      strncpy(us_token, yytext+1, 255); 
      us_token[strlen(us_token)-1] = '\0';
      yyin_temp = fopen(us_token, "r");
   
      if ( ! yyin_temp )
      {
         yyerror("Warning, can't open include file (%s).", us_token);
      }
      else
      {
         include_stack[include_stack_ptr++].buffer = YY_CURRENT_BUFFER;
	 include_stack[include_stack_ptr-1].line_number = line_number;
	 strncpy(include_stack[include_stack_ptr-1].filename, filename, 255);
	 
	 strncpy(filename, us_token, 255);
	 
         yyin = yyin_temp;
         yy_switch_to_buffer(yy_create_buffer( yyin, YY_BUF_SIZE ) );
      }
      
      BEGIN(INITIAL);
   }
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "config/actions/actions.l"
{   strncpy(us_token, yytext+1, 255); 
		    us_token[strlen(us_token)-1] = '\0';
		    return(T_STRING); 
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_LOG_LEX); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 102 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_LOG_LEX); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "config/actions/actions.l"
{   return(T_VAR_LEX); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 104 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_EVENT_LEX); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 105 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_ONLINE_LEX); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_FOR_LEX); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MESSAGE_LEX); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 108 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MESSAGE_LEX); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 109 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MESSAGE_LEX); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 110 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MESSAGE_LEX); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 111 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_STOP_LEX); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 112 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MAIL_LEX); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 113 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_MAIL_LEX); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 114 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_RUN_LEX); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 115 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_WITH_LEX); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 116 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_USING_LEX); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 117 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_OFFLINE_LEX); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 118 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_SAVEBASIC_LEX); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 119 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_SEARCH_LEX); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 120 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_STATUS_LEX); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 121 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_ANY_LEX); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 122 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_REGISTRATION_LEX); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 123 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_RDBMS_FAIL_LEX); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 124 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_RDBMS_ERR_LEX); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 125 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_INTERNAL_ERR_LEX); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 126 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_PPHUNG_LEX); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 127 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_ONLINE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 128 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_OFFLINE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 129 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_FFCH); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 130 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_PRIVACY); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 131 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_DND); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 132 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_AWAY); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 133 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_OCCUPIED); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 134 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_S_NA); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 135 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_ACTIONS) return(T_ANY_LEX); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_RATE_LEX); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 138 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_CLASS_LEX); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_CLASSES_LEX); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 140 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_SNAC_LEX); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 141 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_FAMILY_LEX); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 142 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_INDEX_LEX); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_VERSION_LEX); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_SUBTYPE_LEX); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 145 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_NUMBER_LEX); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "config/actions/actions.l"
{   if (config_file_type == CONFIG_TYPE_AIM) return(T_NUMBER_LEX); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 147 "config/actions/actions.l"
{   strncpy(us_token, "1", 255); return(T_DIGITS); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 148 "config/actions/actions.l"
{   strncpy(us_token, "0", 255); return(T_DIGITS); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 150 "config/actions/actions.l"
BEGIN(incl);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 "config/actions/actions.l"
{   strncpy(us_token, yytext, 255); 
		    strncpy(iname, yytext, 255);
		    return(T_IDENT); 
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 156 "config/actions/actions.l"
{   strncpy(us_token, yytext, 255); return(T_DIGITS); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 157 "config/actions/actions.l"
{   strncpy(us_token, yytext, 255); return(T_DIGITS16); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 158 "config/actions/actions.l"
{   strncpy(us_token, yytext, 255); return(T_WRONG_IDENT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "config/actions/actions.l"
{   /* SKIPED */; line_number++; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 160 "config/actions/actions.l"
{   /* SKIPED */; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
#line 162 "config/actions/actions.l"
{

   if ( --include_stack_ptr < 0 )
   {
      yyterminate();
   }
   else
   {
      yy_delete_buffer( YY_CURRENT_BUFFER ); fclose(yyin);
      yy_switch_to_buffer(include_stack[include_stack_ptr].buffer);
      line_number = include_stack[include_stack_ptr].line_number;
      strncpy(filename, include_stack[include_stack_ptr].filename, 255);
   }
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 177 "config/actions/actions.l"
ECHO;
	YY_BREAK
#line 1324 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 177 "config/actions/actions.l"

void skipcmnts ()
{
   int lexem;
   for (;;) 
   {
      lexem = input();
      while (lexem != '*') 
      {
         if (lexem == '\n') line_number++;
         lexem = input();
      }
      
      lexem = input();
      if (lexem == '\n') line_number++;
      
      if (lexem != '/') 
      {
         unput(yytext[yyleng-1]);
      }
      else return;
   }
}

void skipcmnts2 ()
{
   for (;;) 
   {
      while (input() != '\n');
      line_number++;
      return;
   }
}
