n 1001			uin
s password		passwd
n 0			disabled
n 0			lastlogin
n 0			ip_addr
n 0			can_broadcast
n 0			cr_date
n 0			ch_password
s Admin			nick
s Admin			first
s none			last
s admin@localhost	email1
s none			email2
s none			email3
n 0			pemail1
n 0			gmt_offset
n 1 			auth
n 2			gender
n 0			age
n 31			bday
n 12			bmonth
n 2000			byear
s unpublished		waddr
s none			wcity
s none			wstate
n 0			wcountry
s HomeNet		wcompany
s SysAdmin		wtitle
n 0			wocup
s none			wdepart
s unpublished		wphone
s unpublished		wfax
s unpublished		wpager
s none			wzip
s http://localhost	wpage
s none			notes
s none			haddr
s none			hcity
s none			hstate
n 0			hcountry
s unpublished		hphone
s unpublished		hfax
s unpublished		hcell
s none			hzip
s http://localhost	hpage
n 0			martial
s none			wzip2
s none			hzip2
n 0			bcountry
s none			bstate
s none			bcity
